### ISSUE TITLE
Block Timer Display

### ISSUE THREAD

**Issue by swoobie** [euthyphro666/proto-ninja#17]
Add some kind of GUI element that visualizes the Block ability is ready to use, when it's on cooldown, and the remaining progress left before it can be used again.

**Comment by sentient-soup** [comment]
Should this and #16 be GUI based or animation based? It would be super easy to tack below the current health bar. But that might play weird if the player has to glance up the screen to know if a block is ready. If we rolled blocking and dashing into some stamina ability I think that would make the most sense. Otherwise, we could simply have a clear point in the animation that flags to the player that it's ready.

**Comment by swoobie** [comment]
I was thinking a mini loading bar underneath the actual player would work temporarily, and then we could determine if it should be animation based or not later?
